module.exports = {
	CONNECTION: 'connection',
	MESSAGE_SENT: 'MESSAGE_SENT',
	RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
	USER_IS_TYPING: 'USER_IS_TYPING',
	RECEIVE_TYPING_USER: 'RECEIVE_TYPING_USER',
	USER_IS_NOT_TYPING: 'USER_IS_NOT_TYPING',
	RECEIVE_NON_TYPING_USER: 'RECEIVE_NON_TYPING_USER'
}